# MySQL. Versions 5.5.8 and up are supported.
#
# Install the MySQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   https://dev.mysql.com/doc/refman/5.7/en/password-hashing.html
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: db # development, test 用にComposeのPostgreSQLを指す
  username: postgres
  password: password

development:
  <<: *default
  database: alchemy_development

test:
  <<: *default
  host: localhost
  database: alchemy_test

production:
  <<: *default
  database: alchemy_production
  username: <%= ENV['DB_USER'] %>
  host: <%= ENV["DB_HOST"] %>
  password: <%= ENV["DB_PASSWORD"] %>
