name: Rails CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1.6'

    - name: Cache Ruby gems
      uses: actions/cache@v3
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Install dependencies
      run: |
        sudo apt-get update -qq
        gem install bundler
        bundle install

    - name: Run RSpec
      env:
        RAILS_ENV: test
      run: bundle exec rspec

    - name: Run RuboCop
      run: bundle exec rubocop

    - name: Run Brakeman
      run: |
        bundle exec brakeman --no-exit-on-warn
